name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "dckr_pat__4TcZfzpBRIkULIFpd1bhssExQ8" | docker login -u blimbachiyadocker --password-stdin

      - name: Build Docker Image
        run: docker build -t blimbachiyadocker/devops-node-app:latest .

      - name: Push Docker Image
        run: docker push blimbachiyadocker/devops-node-app:latest
